### ISSUE TITLE
Installation of sample app with helm not working

### ISSUE THREAD

**Issue by MuhammadMunir12** [benc-uk/nodejs-demoapp#25]
Hi, 

I am following this guide to run the application is kubernetes environment. 
https://github.com/benc-uk/nodejs-demoapp/blob/master/deploy/kubernetes/readme.md 

But facing the following error: 
```
$ helm repo list
NAME    URL
benc-uk https://benc-uk.github.io/helm-charts


sudo helm install demo benc-uk/webapp --values myapp.yaml
Error: INSTALLATION FAILED: failed to download "benc-uk/webapp"
```

Any help would be really appreciated. 

Secondly, if i don't want to use helm charts, what's the alternate way to run this application in k8s?

Looking forward to hear from you.

**Comment by benc-uk** [comment]
I just tried the helm commands same as you but had no issues, maybe `helm repo update` would help?

If you don't want to use helm the simplest way would be to run it directly as a pod, then expose the traffic using a LoadBalancer service

```bash
kubectl run nodeapp --restart=Never --image=ghcr.io/benc-uk/nodejs-demoapp:4.8.6
kubectl expose pod nodeapp --port=80 --target-port=3000 --type=LoadBalancer
```

Run `kubectl get svc` to get the external IP of the service
